plugins:
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-default-layout
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
  - _projects
  - _guides

# Site Settings
locale                   : "en-US"
title                    : "Homepage Hell"
title_separator          : "-"
name                     : &name "bleb" # &name is a YAML anchor which can be *referenced later
description              : &description "Bleeeeh"
url                      : https://reakain.github.io # the base hostname & protocol for your site e.g. "https://reakain.github.io"
baseurl                  : "/jekyll_test" # the subpath of your site, e.g. "/blog."
repository               : "reakain/jekyll_test"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
# breadcrumbs            : false # true, false (default)


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Collections
collections:
  projects:
    output: true
    title: Project Listing
    permalink: /:collection/:path/
    toc: true
  guides:
    output: true
    title: Guides Listing
    permalink: /:collection/:path/
    toc: true


# Defaults
defaults:
  - scope: 
      path: "*/*.md"
    values:
      layout: "default"
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: default
  # _guides
  - scope:
      path: ""
      type: guides
    values:
      layout: default

# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: America/New_York # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones