plugins:
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-default-layout
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

defaults:
  -
    scope: 
      path: "*.md"
    values:
      layout: "default"

collections:
  projects:
    output: true
    title: Project Listing
    permalink: /:projects/
    layout: "default"
  guides:
    output: true
    title: Guides Listing
    permalink: /:guides/
    layout: "default"